Dev
nick-chal/react-todo pull request #1
Opened 2019-01-10 14:17 UTC by nick-chal

Addition and basic toggle added.
Three options shown
Remaining - delete, edit and search

2019-01-10 17:05 UTC, SafalPandey requested changes

2019-01-10 17:05 UTC, SafalPandey commented on src/assets/css/styles.js
> +import './reset.css';
This import doesn't look right. You should import `reset.css` before importing other css files.

2019-01-10 17:05 UTC, SafalPandey commented on src/components/App.js
>  import '../assets/css/App.css';
You're importing `App.css` twice here. Once in this line and then again in `styles.js`.

2019-01-10 17:05 UTC, SafalPandey commented on src/components/TodoForm.js
> +      <>
No need to use fragments here.

2019-01-10 17:05 UTC, SafalPandey commented on src/components/TodoForm.js
> +    if (/\S/.test(this.state.text)) {
Add a newline before if statements.
Create a utility function like `isValidText` that wraps this logic to make it more readable.

2019-01-10 17:05 UTC, SafalPandey commented on src/components/TodoList.js
> +  toggleShowState = showState => {
`set` would be a better name than `toggle`.

2019-01-10 17:05 UTC, SafalPandey commented on src/components/TodoList.js
> +    return (
Add newline before return statement.

2019-01-10 17:05 UTC, SafalPandey commented on src/components/TodoList.js
> +          <button
If you're keeping all the buttons, form and the list under this component, the name `TodoList` becomes a bit misleading.
Try moving everything except the actual list to `App` component you'll learn a thing or two in the process. :slightly_smiling_face:

2019-01-11 05:21 UTC, cham11ng commented on src/components/TodoList.js
> +import React from 'react';
Add one line to separate package import and app import.

2019-01-11 11:14 UTC, closed without merging